# Generated by Django 3.0.6 on 2020-06-05 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resultado_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='user_id',
            new_name='user',
        ),
    ]
